# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "bento/ubuntu-20.04"
    server.vm.network "private_network",ip:"192.168.5.2"
    server.vm.hostname = "tb-server"
    server.vm.define "tb-server"
    server.vm.synced_folder "../", "/home/vagrant/timebase"
    server.vm.provision :shell, path: "server-bootstrap.sh"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
  config.vm.define "dmz" do |dmz|
    dmz.vm.box = "bento/ubuntu-20.04"
    dmz.vm.network "private_network",ip:"192.168.5.3"
    dmz.vm.hostname = "tb-dmz"
    dmz.vm.define "tb-dmz"
    dmz.vm.synced_folder "../", "/home/vagrant/timebase"
    dmz.vm.provision :shell, path: "dmz-bootstrap.sh"
    dmz.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "bento/ubuntu-20.04"
    client.vm.network "private_network",ip:"192.168.5.4"
    client.vm.hostname = "tb-client"
    client.vm.define "tb-client"
    client.vm.synced_folder "../", "/home/vagrant/timebase"
    client.vm.provision :shell, path: "client-bootstrap.sh"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
end
